### PR TITLE
Update QuickNet documentation.

### PR DESCRIPTION
**Pull request by AdamHillier**
This is a draft as we need to take new benchmarks using the 0.6 release.

### CODE REVIEW

**Comment by AdamHillier** [comment]
Will resolve https://github.com/larq/compute-engine/discussions/662.

**Comment by simonmaurer** [comment]
I can provide numbers for mac mini (Apple M1) that we could directly add here. so an additional commit on this [PR](https://github.com/larq/compute-engine/pull/664) for the ReadMe.md is not needed.

**Comment by simonmaurer** [comment]
Here's the latency results for the [Apple mac mini 2020 (Apple M1)](https://www.apple.com/uk/mac-mini/) using the latest LCE benchmark [v0.6](https://github.com/larq/compute-engine/releases/tag/v0.6.0) including this [PR](https://github.com/larq/compute-engine/pull/664)

The table below presents **single-threaded**/**multi-threaded** performance of Larq Compute Engine [v0.6](https://github.com/larq/compute-engine/releases/tag/v0.6.0) on
different versions of a novel BNN model called QuickNet (trained on ImageNet dataset, released on [Larq Zoo](https://docs.larq.dev/zoo/))
on an [Apple mac mini 2020 (Apple M1)](https://www.apple.com/uk/mac-mini/):

| Model                                                                                                                                                                      | Top-1 Accuracy | mac mini M1, ms (1 thread) | mac mini M1, ms (1 thread - XNNPACK) |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :------------: | :--------------------: | :--------------------: |
| [QuickNetSmall](https://docs.larq.dev/zoo/api/sota/#quicknetsmall) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_small_weights.h5))                        |     59.4 %     |          4.0          |          3.5          |
| [QuickNet](https://docs.larq.dev/zoo/api/sota/#quicknet) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_weights.h5)) |     63.3 %     |          5.8          |          5.4          |
| [QuickNetLarge](https://docs.larq.dev/zoo/api/sota/#quicknetlarge) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_large_weights.h5))             |     66.9 %     |          9.9          |          9.5          |

| Model                                                                                                                                                                      | Top-1 Accuracy | mac mini M1, ms (4 threads) | mac mini M1, ms (4 threads, XNNPACK) |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :------------: | :--------------------: | :--------------------: |
| [QuickNetSmall](https://docs.larq.dev/zoo/api/sota/#quicknetsmall) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_small_weights.h5))                        |     59.4 %     |          1.8          |          1.9          |
| [QuickNet](https://docs.larq.dev/zoo/api/sota/#quicknet) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_weights.h5)) |     63.3 %     |          2.5          |          2.6          |
| [QuickNetLarge](https://docs.larq.dev/zoo/api/sota/#quicknetlarge) ([.h5](https://github.com/larq/zoo/releases/download/quicknet-v1.0/quicknet_large_weights.h5))             |     66.9 %     |          3.9          |          4.1          |

**Review by lgeiger — CHANGES_REQUESTED** [review]
How do you feel about removing the links to the `*.h5` files completely from the README here? I think these were useful when some of the models weren't available on Larq Zoo yet, but I don't think these add any value currently.

**Comment by AdamHillier** [comment]
Nice, yeah I've removed the h5 links now. I don't have my RPi to hand so can't record new benchmarks atm, but will update those numbers by tomorrow.

**Review by Tombana — APPROVED** [review]

**Review by lgeiger — APPROVED** [review]

**Pull request merged**
