### PR TITLE
:arrow_up: tensorflow@2.6.2

### LINKED ISSUE #680: Upgrade TensorFlow dependency to 2.6
The TensorFlow 2.6 stable has been released. It would be good to upgrade to this release at some point.

### PR DESCRIPTION
**Pull request by lgeiger**
## What do these changes do?
This PR updates LCE to TensorFlow 2.6.1.

## How Has This Been Tested?
This has not been tested yet, let's see what CI thinks about it.

## Related issue number
Fixes #680

### CODE REVIEW

**Review by CNugteren — APPROVED** [review]
Looks good to me. Have you ran some basic benchmarks to make sure there are no speed regressions?

**Comment by lgeiger** [comment]
> Looks good to me. Have you ran some basic benchmarks to make sure there are no speed regressions?

Not yet. I am also seeing some test failures locally which do not seem to reproduce on CI. Though I haven't had time to investigate yet.

**Comment by lgeiger** [comment]
> Not yet. I am also seeing some test failures locally which do not seem to reproduce on CI. Though I haven't had time to investigate yet.

The conversion crash I was experiencing locally was in this test:
https://github.com/larq/compute-engine/blob/06d6ecefae07b294ab459949906dbe226bbd018b/larq_compute_engine/tests/end2end_test.py#L231-L257
with the `toy_model`, `convert_keras_model` and `experimental_default_int8_ranges`. In the past we've seen that the `experimental_default_int8_ranges` flag can be buggy and given that this only happens locally and in the fallback `convert_keras_model` path and not using the saved model based converter, I am happy to call this PR ready for review.

I will run some basic benchmarks at some point to ensure that we haven't introduced any regressions at which point we should be able to merge this PR.

**Comment by luciengaitskell** [comment]
@lgeiger Might also want to rename the PR 😄

**Review by Tombana — APPROVED** [review]

**Comment by lgeiger** [comment]
I benchmarked the quicknet family models on my Pixel 5 phone with 1 and 4 threads and didn't see a performance regression. So I think this PR is good to go from my side.

**Pull request merged**
